actionにFILTERを追加
pepabo/siteguard_lite-custom_signature pull request #5
Opened 2020-09-29 07:58 UTC by hayasaki-shunsuke

sig_custom.yml に設定するActionについて、
```
validates :action, inclusion: %w(BLOCK NONE WHITE) # TODO support FILTER action
```
とあり、`FILTER` が指定出来ない状態だったので追加します。

2020-10-19 06:23 UTC, hayasaki-shunsuke commented
## bin/console で確認
### sig_custom.yml
```
rules:
- name: filter-60sec
  action: FILTER
  filter_lifetime: 1800
  exclusion_action: EXCLUDE_OFFICIAL
  comment: 接続拒否時間60秒
  conditions:
    - key: URL
      value: .*user\.test\.jp/.*
      comparison_methods:
        - PCRE_CASELESS
        - AND
        - COUNTER(60:30)
```

```
irb(main):002:0> irb(main):002:0> rules = SiteguardLite::CustomSignature.load_yaml(File.read('sig_custom.yml'))
=> [#<SiteguardLite::CustomSignature::Rule:0x00007f8f8fa1e3b8 @name="filter-60sec", @comment="接続拒否時間60秒", @exclusion_action="EXCLUDE_OFFICIAL", @signature=nil, @action="FILTER", @filter_lifetime=1800, @enable=true, @conditions=[#<SiteguardLite::CustomSignature::Condition:0x00007f8f8fa1e368 @key="URL", @value=".*user\\.test\\.jp/.*", @comparison_methods=["PCRE_CASELESS", "AND", "COUNTER(60:30)"]>]>]
irb(main):003:0> SiteguardLite::CustomSignature.dump_text(rules)
=> "ON\tFILTER:1800\t\tfilter-60sec\tURL\tPCRE_CASELESS,AND,COUNTER(60:30)\t.*user\\.test\\.jp/.*\t\t接続拒否時間60秒\n"
```

2020-10-20 07:47 UTC, kenchan requested changes
名前付けと、インタフェースの設計について気になったのでコメントをしました。

2020-10-20 07:47 UTC, kenchan commented on lib/siteguard_lite/custom_signature/condition.rb
> +      def to_action_filter_lifetime(action, filter_lifetime)
`to_xxx`というメソッド名からは、このオブジェクトを`xxx`にした表現を返すという意味になるので、名前が適切ではないように思います。ここ以外の部分も同様です。何か大体案となるよう名前は思いつきますか？

2020-10-20 07:47 UTC, kenchan commented on lib/siteguard_lite/custom_signature/condition.rb
> +        action.include?('FILTER') ? action + ':' + filter_lifetime.to_s : action
`==`ではなく、`include?`で判定している意図はなんでしょうか？他のファイルにも同様の判定があるのでそこもあわせて意図があれば教えてください。

2020-10-20 07:47 UTC, kenchan commented on lib/siteguard_lite/custom_signature/rule.rb
> +      attr_accessor :exclusion_action, :signature, :action, :filter_lifetime
actionやfilter_lifetimeは`attr_reader`ではなく`attr_accessor`である必要はありますか？また、必要であるなら、`action`を`attr_reader`から削除してほしいです。

2020-10-20 07:47 UTC, kenchan commented on lib/siteguard_lite/custom_signature/rule.rb
> +        @filter_lifetime = args[:filter_lifetime] || '300' # default 300sec
FILTER以外のactionの場合もこの値が入ってしまいます。望ましいのは、FILTERのときはデフォルトが300、それ以外のときはnilかなと思いましたが、どう思いますか？

2020-10-21 00:35 UTC, hayasaki-shunsuke commented on lib/siteguard_lite/custom_signature/rule.rb
> +        @filter_lifetime = args[:filter_lifetime] || '300' # default 300sec
>望ましいのは、FILTERのときはデフォルトが300、それ以外のときはnilかなと思いましたが、どう思いますか？

同じ認識です。デフォルトが300、それ以外のときはnilになるように修正しました。

2020-10-21 00:38 UTC, hayasaki-shunsuke commented on lib/siteguard_lite/custom_signature/condition.rb
> +      def to_action_filter_lifetime(action, filter_lifetime)
関数名がわかりにくかったので修正しました。
https://github.com/pepabo/siteguard_lite-custom_signature/pull/5/files#diff-2bb7116851942f1ba5613f426c5bf27a179d1c6f9f86a31324bff5510945bf3cR56
https://github.com/pepabo/siteguard_lite-custom_signature/pull/5/files#diff-2ba1e9f228b546758b7ddb3b862af54ee143e4e8048dc52e28895c50f4a45043R65-R71

2020-10-21 00:41 UTC, hayasaki-shunsuke commented on lib/siteguard_lite/custom_signature/condition.rb
> +        action.include?('FILTER') ? action + ':' + filter_lifetime.to_s : action
`FILTER:1800` を`FILTER` と`1800` に分割する箇所を修正しました。

比較する文字列が`FILTER` の場合は `==` で判定しているのですが、`FILTER:1800` と比較する場合に`include?` で判定しています。

2020-10-21 00:48 UTC, hayasaki-shunsuke commented on lib/siteguard_lite/custom_signature/rule.rb
> +      attr_accessor :exclusion_action, :signature, :action, :filter_lifetime
>actionやfilter_lifetimeはattr_readerではなくattr_accessorである必要はありますか？

FILTER:1800 をFILTER と1800 に分割する箇所を修正し、
`action` を `attr_accessor ` に指定しました。
```rb
attr_reader :name, :comment, :enable, :conditions, :filter_lifetime
attr_accessor :action, :exclusion_action, :signature
```

理由としては、
https://github.com/pepabo/siteguard_lite-custom_signature/pull/5/files#diff-2bb7116851942f1ba5613f426c5bf27a179d1c6f9f86a31324bff5510945bf3cR21
の箇所にて actionの文字列にfilter_lifetimeの数値を書き込む必要があるからです。

>また、必要であるなら、actionをattr_readerから削除してほしいです。

こちら修正漏れでした。

2020-10-21 00:54 UTC, hayasaki-shunsuke commented on lib/siteguard_lite/custom_signature/condition.rb
> +        rule.action = add_param_filter_lifetime(rule.action, rule.filter_lifetime) if rule.action == ('FILTER')
action= FILTER , filter_lifetime =1800 の場合、`FILTER:1800` のように整形する必要がある。
FILTERの時のみ数値を追加するので、add_param_filter_lifetimeという表現にして
rule.action を渡している。

```
ON	FILTER:1800		filter-60sec	URL	PCRE_CASELESS,AND,COUNTER(60:30)	.*user\.test\.jp/.*		接続拒否時間60秒
```

2020-10-21 00:55 UTC, hayasaki-shunsuke commented on lib/siteguard_lite/custom_signature/rule.rb
> +      validates :action, inclusion: %w(BLOCK NONE WHITE FILTER)
actionにFILTERを追加できるようにvalidatesに指定。

2020-10-21 00:56 UTC, hayasaki-shunsuke commented on lib/siteguard_lite/custom_signature/text_line_parser.rb
> +          filter_lifetime: parse_filter_lifetime(fields[1]),
`FILTER:1800` の文字列を
action= FILTER , filter_lifetime =1800 に分割する処理はここで行うように修正した。

2020-10-21 00:56 UTC, hayasaki-shunsuke commented on lib/siteguard_lite/custom_signature/version.rb
> +    VERSION = "0.5.0"
"0.5.0" で良いか確認する。

2020-10-21 00:58 UTC, hayasaki-shunsuke commented on spec/fixtures/sig_custom.yaml
> +          - COUNTER(60:30)
action: FILTERの場合、filter_lifetime: 1800 のようにパラメータを追加する。
action: FILTER で filter_lifetimeが指定されていない場合、デフォルトで300が入るように修正した。

2020-10-21 01:14 UTC, hayasaki-shunsuke commented on lib/siteguard_lite/custom_signature/text_line_parser.rb
> +      end
parsed_actionには `FILTER:1800` で文字が渡ってくるのでinclude?('FILTER') で比較している。

2020-10-21 01:18 UTC, kenchan commented on lib/siteguard_lite/custom_signature/rule.rb
> +      attr_accessor :exclusion_action, :signature, :action, :filter_lifetime
なるほど。ここ、`action`を持つオブジェクトがよくないのかなぁ。Ruleの外側からActionを変更させるのはあまり意図していなかったのであとで設計を見直したほうがいいと思いました。（私が

2020-10-21 01:44 UTC, kenchan requested changes

2020-10-21 01:44 UTC, kenchan commented on lib/siteguard_lite/custom_signature/text_line_parser.rb
> +      end
`String#delete`は引数の文字列を削除するのではなく、引数の文字列に含まれているすべて文字をすべて取り除くメソッドです。ちょっとわかりにくいので例を出しておきます。

```
irb(main):003:0> "FFILTERF".delete("FILTER")
=> ""
```

現実問題としては問題が起きない可能性はたかいですが、意図しない挙動のもとになるので別の方法は考えられますか？

2020-10-21 01:44 UTC, kenchan commented on lib/siteguard_lite/custom_signature/text_line_parser.rb
> +        parsed_action.include?('FILTER') ? 'FILTER' : parsed_action
ここも実際には問題がないのですが、`String#include?`で判定すると`FFILTERR`みたいなものも`FILTER`になってしまいますがどう思いますか？また、FILTER対応の設計判断が必要になるなと思ったので自分の考えを書きます。

まず、文字列を分割するというこのクラスの責務の範囲において、分割のやりかたとして3つの方法を考えました。

1. `String#start_with?`を使って`start_with?('FILTER:')`で判定する仕様にする
2. `^FILTER:\d+$`というようなFILTERで正しいフォーマットかどうかを厳密に判定する仕様にする
3. コロンが含まれていたときにはコロンまでをactionとする仕様にする

これは、TextLineParserがどこまでの責務を持つかというところを決める判断だと思っています。

3の考えとしては、今までのTextLineParserは、actionにどういう文字列が来るかは知りません。それは、RuleクラスやConditionクラスの責務だからです。このクラスは、一行のフォーマット（文法）を解釈し、それぞれの部分に分けることなので、Actionの部分には`#{Action}:#{Option}`というフォーマットの文字列がきることだけを知っていれば十分ではないかと思います。

一方で1や2の方法では、TextLineParserはActionに`FILTER`という文字列がくることを知ることになります。この設計判断を下すのであれば、同様に他のActionの文字列の判定もこのクラスの責務となる可能性があります。つまり、文字列を分割することと、その意味を解釈することをこのクラスの責務とするということです。（後々ね）

3はより汎用的な仕組みになりますが、少なくとも現時点ではFILTER以外にこの仕組みを使うことはないので、過剰な抽象化になる可能性があります(こちらの場合、filter_filetimeというfilterに特化した名前づけはやめるという判断になると思います)。1や3の場合は、その逆でより具象に合わせた設計をするということです。

このPull Requestの中で対応するかはおいておいて、どうあると良いと思いますか？

2020-10-21 01:46 UTC, kenchan commented on lib/siteguard_lite/custom_signature/version.rb
> +    VERSION = "0.5.0"
非互換な挙動はなく、機能追加になるのでminorバージョンアップで良いと思いました。

2020-10-21 03:51 UTC, kenchan approved these changes
ペアプロで何箇所かリファクタリングしたのでApproveします！

2020-10-21 03:58 UTC, merged